# Change these first
owner: mine-at # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

assignees:
  - mine-at

sites:
    - name: Mining Stratum
      url: solo.maxhash.io
      port: 3333
      check: "tcp-ping"
    - name: Dashboard
      url: https://maxhash.io/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.maxhash.io
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: maxhash.io
  introTitle: "Global status for maxhash.io"
  introMessage: Monitor mining pool service status and statistics.
  navbar:
    - title: Home
      href: https://maxhash.io
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
